# Generated by Django 4.0.3 on 2022-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_test_preparations_alter_test_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='CH_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalspecialistes',
            name='Sid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
